### ISSUE TITLE
Keyboard input method feedback

### ISSUE THREAD

**Issue by liyuanrui** [chaquo/chaquopy-console#3]
Hello everyone, I found that using the console input will default to the English input, switching back to the Chinese input every time. I think it is interesting and consistent with the console writing commands, but sometimes users may have their own native language to input ideas. The problem is not big, but still feedback it ~

**Comment by mhsmith** [comment]
Good point, thanks. This will be because we used `textVisiblePassword` to suppress predictions, which makes sense in the REPL, but not necessarily in other console apps.

**Comment by mhsmith** [comment]
Until we fix this, you can edit your own copy of activity_console.xml.

**Comment by liyuanrui** [comment]
ok, i do it, thanks

**Comment by mhsmith** [comment]
This is fixed in the current version.
