### ISSUE TITLE
not able to get *.py file

### ISSUE THREAD

**Issue by anshul3485raj** [chaquo/chaquopy-console#4]
I did every step that you showed in chaquo documentation  , im not able to get *.py file

**Comment by mhsmith** [comment]
From [StackOverflow](https://stackoverflow.com/questions/61314889):

> guys i read ad setup android studio with chaquo for python support but python community edition says no interpreter , will my build have python code executing ??. 

This message is harmless, and so are any messages about undefined names. Just go ahead and run your app, and if there really is an error, the details will be displayed in the [Logcat](https://developer.android.com/studio/debug/am-logcat.html).

> I want to call *.py file from A java file by pressing a button Will intent and startactivity(Intenet) will help in it . my *py is An AI for performing some task. and I want when user ask for making phone call then I want to call java file to make a phone call . pls help me I already read java API implementation. 

Have a look at the [JavaDemoActivity](https://github.com/chaquo/chaquopy/blob/master/app/src/main/java/com/chaquo/python/demo/JavaDemoActivity.java) for an example of calling Python from within an Android user interface. Or for a larger Kotlin-based example, have a look at [Electron Cash](https://github.com/Electron-Cash/Electron-Cash/tree/master/android).

> and I want tensorflow==1.5.0 but chaquopy have only tensorflow>=2 but version 2 wont work on my pc any solution for this

We currently only offer TensorFlow versions 1.10.1 (for Chaquopy 6 and older) or 2.1.0 (for Chaquopy 7 and newer). It should be possible to make your code compatible with one of those versions with minimal changes.

**Comment by anshul3485raj** [comment]
thanks for help . just placing *.py file in python dir will it work ?

**Comment by mhsmith** [comment]
Yes, just as this chaquopy-console app demonstrates.

**Comment by mhsmith** [comment]
If you have any futher issues, please post them in [the main project](https://github.com/chaquo/chaquopy/issues).
