### ISSUE TITLE
python file went missing after cloning repository.

### ISSUE THREAD

**Issue by TheRadioDept** [chaquo/chaquopy-console#6]
Hello. 

After I cloned this application and opened it in my Android Studio all Python files disappeared. I can see where they should be looking at your version, but they are just went missing after I opened it on my machine. 

I tried deleting it and downloading again, but still problem remains. 

![Screenshot from 2022-11-06 20-45-15](https://user-images.githubusercontent.com/58568149/200183413-968b6ce8-73a0-454e-9636-9d6c2397c419.png)

Thanks in advance.

**Comment by mhsmith** [comment]
The "Android" mode of the Project pane only displays files which Android Studio knows about, which doesn't include Python files. If you click "Android" at the top left and change it to "Project Files", then you should see everything.
